'use strict';

angular.module('hhupApp').service('nationalitiesService', function($q) {

  this.nationalities =
  [
    {
      flag: 'flag ad',
      code: 'ad',
      ctry: 'Andorra',
      natn: 'Andorran',
    },
    {
      flag: 'flag ae',
      code: 'ae',
      ctry: 'United Arab Emirates',
      natn: 'Emirian',
    },
    {
      flag: 'flag af',
      code: 'af',
      ctry: 'Afghanistan',
      natn: 'Afghan',
    },
    {
      flag: 'flag ag',
      code: 'ag',
      ctry: 'Antigua and Barbuda',
      natn: 'Antiguans or Barbudans'
    },
    {
      flag: 'flag al',
      code: 'al',
      ctry: 'Albania',
      natn: 'Albanian',
    },
    {
      flag: 'flag am',
      code: 'am',
      ctry: 'Armenia',
      natn: 'Armenian',
    },
    {
      flag: 'flag an',
      code: 'an',
      ctry: 'Netherlands Antilles',
      natn: 'Netherlands Antilles',
    },
    {
      flag: 'flag ao',
      code: 'ao',
      ctry: 'Angola',
      natn: 'Angolan',
    },
    {
      flag: 'flag aq',
      code: 'aq',
      ctry: 'Antarctica',
      natn: 'Antarctican',
    },
    {
      flag: 'flag ar',
      code: 'ar',
      ctry: 'Argentina',
      natn: 'Argentinean',
    },
    {
      flag: 'flag as',
      code: 'as',
      ctry: 'American Samoa',
      natn: 'Samoan (Am.)',
    },
    {
      flag: 'flag at',
      code: 'at',
      ctry: 'Austria',
      natn: 'Austrian',
    },
    {
      flag: 'flag au',
      code: 'au',
      ctry: 'Australia',
      natn: 'Australian',
    },
    {
      flag: 'flag aw',
      code: 'aw',
      ctry: 'Aruba',
      natn: 'Aruban',
    },
    {
      flag: 'flag ax',
      code: 'ax',
      ctry: 'Aland Islands',
      natn: 'Aland Islands',
    },
    {
      flag: 'flag az',
      code: 'az',
      ctry: 'Azerbaijan',
      natn: 'Azerbaijani',
    },
    {
      flag: 'flag ba',
      code: 'ba',
      ctry: 'Bosnia and Herzegovina',
      natn: 'Bosnian or Herzegovinian',
    },
    {
      flag: 'flag bb',
      code: 'bb',
      ctry: 'Barbados',
      natn: 'Barbadian',
    },
    {
      flag: 'flag bd',
      code: 'bd',
      ctry: 'Bangladesh',
      natn: 'Bangladeshi',
    },
    {
      flag: 'flag be',
      code: 'be',
      ctry: 'Belgium',
      natn: 'Belgian',
    },
    {
      flag: 'flag bf',
      code: 'bf',
      ctry: 'Burkina Faso',
      natn: 'Burkinabe',
    },
    {
      flag: 'flag bg',
      code: 'bg',
      ctry: 'Bulgaria',
      natn: 'Bulgarian',
    },
    {
      flag: 'flag bh',
      code: 'bh',
      ctry: 'Bahrain',
      natn: 'Bahraini',
    },
    {
      flag: 'flag bi',
      code: 'bi',
      ctry: 'Burundi',
      natn: 'Burundian',
    },
    {
      flag: 'flag bj',
      code: 'bj',
      ctry: 'Benin',
      natn: 'Beninese',
    },
    {
      flag: 'flag bm',
      code: 'bm',
      ctry: 'Bermuda',
      natn: 'Bermudan',
    },
    {
      flag: 'flag bn',
      code: 'bn',
      ctry: 'Brunei Darussalam',
      natn: 'Bruneian',
    },
    {
      flag: 'flag bo',
      code: 'bo',
      ctry: 'Bolivia',
      natn: 'Bolivian',
    },
    {
      flag: 'flag br',
      code: 'br',
      ctry: 'Brazil',
      natn: 'Brazilian',
    },
    {
      flag: 'flag bs',
      code: 'bs',
      ctry: 'Bahamas',
      natn: 'Bahamian',
    },
    {
      flag: 'flag bt',
      code: 'bt',
      ctry: 'Bhutan',
      natn: 'Bhutanese',
    },
    {
      flag: 'flag bv',
      code: 'bv',
      ctry: 'Bouvet Island',
      natn: 'Bouvet Island',
    },
    {
      flag: 'flag bw',
      code: 'bw',
      ctry: 'Botswana',
      natn: 'Batswana', //?
    },
    {
      flag: 'flag by',
      code: 'by',
      ctry: 'Belarus',
      natn: 'Belarusian',
    },
    {
      flag: 'flag bz',
      code: 'bz',
      ctry: 'Belize',
      natn: 'Belizean',
    },
    {
      flag: 'flag ca',
      code: 'ca',
      ctry: 'Canada',
      natn: 'Canadian',
    },
    {
      flag: 'flag cc',
      code: 'cc',
      ctry: 'Cocos (Keeling) Islands',
      natn: 'Cocos (Keeling) Islands',
    },
    {
      flag: 'flag cd',
      code: 'cd',
      ctry: 'Democratic Republic of the Congo',
      natn: 'Congolese',
    },
    {
      flag: 'flag cf',
      code: 'cf',
      ctry: 'Central African Republic',
      natn: 'Central African',
    },
    {
      flag: 'flag cg',
      code: 'cg',
      ctry: 'Congo',
      natn: 'Congolese',
    },
    {
      flag: 'flag ch',
      code: 'ch',
      ctry: 'Switzerland',
      natn: 'Swiss',
    },
    {
      flag: 'flag ci',
      code: 'ci',
      ctry: 'Cote D\'Ivoire (Ivory Coast)',
      natn: 'Cote D\'Ivoire (Ivory Coast)',
    },
    {
      flag: 'flag ck',
      code: 'ck',
      ctry: 'Cook Islands',
      natn: 'Cook Islands',
    },
    {
      flag: 'flag cl',
      code: 'cl',
      ctry: 'Chile',
      natn: 'Chilean',
    },
    {
      flag: 'flag cm',
      code: 'cm',
      ctry: 'Cameroon',
      natn: 'Cameroonian',
    },
    {
      flag: 'flag cn',
      code: 'cn',
      ctry: 'China',
      natn: 'Chinese',
    },
    {
      flag: 'flag co',
      code: 'co',
      ctry: 'Colombia',
      natn: 'Colombian',
    },
    {
      flag: 'flag cr',
      code: 'cr',
      ctry: 'Costa Rica',
      natn: 'Costa Rican',
    },
    {
      flag: 'flag cs',
      code: 'cs',
      ctry: 'Serbia and Montenegro',
      natn: 'Serbian or Montenegroean',
    },
    {
      flag: 'flag cu',
      code: 'cu',
      ctry: 'Cuba',
      natn: 'Cuban',
    },
    {
      flag: 'flag cv',
      code: 'cv',
      ctry: 'Cape Verde',
      natn: 'Cape Verde',
    },
    {
      flag: 'flag cx',
      code: 'cx',
      ctry: 'Christmas Island',
      natn: 'Christmas Island',
    },
    {
      flag: 'flag cy',
      code: 'cy',
      ctry: 'Cyprus',
      natn: 'Cypriot',
    },
    {
      flag: 'flag cz',
      code: 'cz',
      ctry: 'Czech Republic',
      natn: 'Czech',
    },
    {
      flag: 'flag de',
      code: 'de',
      ctry: 'Germany',
      natn: 'German',
    },
    {
      flag: 'flag dj',
      code: 'dj',
      ctry: 'Djibouti',
      natn: 'Djibouti',
    },
    {
      flag: 'flag dk',
      code: 'dk',
      ctry: 'Denmark',
      natn: 'Danish',
    },
    {
      flag: 'flag dm',
      code: 'dm',
      ctry: 'Dominica',
      natn: 'Dominican',
    },
    {
      flag: 'flag do',
      code: 'do',
      ctry: 'Dominican Republic',
      natn: 'Dominican',
    },
    {
      flag: 'flag dz',
      code: 'dz',
      ctry: 'Algeria',
      natn: 'Algerian',
    },
    {
      flag: 'flag ec',
      code: 'ec',
      ctry: 'Ecuador',
      natn: 'Ecuadorean',
    },
    {
      flag: 'flag ee',
      code: 'ee',
      ctry: 'Estonia',
      natn: 'Estonian',
    },
    {
      flag: 'flag eg',
      code: 'eg',
      ctry: 'Egypt',
      natn: 'Egyptian',
    },
    {
      flag: 'flag eh',
      code: 'eh',
      ctry: 'Western Sahara',
      natn: 'Western Sahara',
    },
    {
      flag: 'flag er',
      code: 'er',
      ctry: 'Eritrea',
      natn: 'Eritrean',
    },
    {
      flag: 'flag es',
      code: 'es',
      ctry: 'Spain',
      natn: 'Spanish',
    },
    {
      flag: 'flag et',
      code: 'et',
      ctry: 'Ethiopia',
      natn: 'Ethiopian',
    },
    {
      flag: 'flag fi',
      code: 'fi',
      ctry: 'Finland',
      natn: 'Finnish',
    },
    {
      flag: 'flag fj',
      code: 'fj',
      ctry: 'Fiji',
      natn: 'Fijian',
    },
    {
      flag: 'flag fk',
      code: 'fk',
      ctry: 'Falkland Islands (Malvinas)',
      natn: 'Falkland Islands (Malvinas)',
    },
    {
      flag: 'flag fm',
      code: 'fm',
      ctry: 'Federated States of Micronesia',
      natn: 'Micronesian',
    },
    {
      flag: 'flag fo',
      code: 'fo',
      ctry: 'Faroe Islands',
      natn: 'Faroe Islands',
    },
    {
      flag: 'flag fr',
      code: 'fr',
      ctry: 'France',
      natn: 'French',
    },
    {
      flag: 'flag fx',
      code: 'fx',
      ctry: 'France, Metropolitan',
      natn: 'French (Metropolitan)',
    },
    {
      flag: 'flag ga',
      code: 'ga',
      ctry: 'Gabon',
      natn: 'Gabonese',
    },
    {
      flag: 'flag gb',
      code: 'gb',
      ctry: 'Great Britain (UK)',
      natn: 'British (UK)',
    },
    {
      flag: 'flag gd',
      code: 'gd',
      ctry: 'Grenada',
      natn: 'Grenadian',
    },
    {
      flag: 'flag ge',
      code: 'ge',
      ctry: 'Georgia',
      natn: 'Georgian',
    },
    {
      flag: 'flag gf',
      code: 'gf',
      ctry: 'French Guiana',
      natn: 'Guyanese',
    },
    {
      flag: 'flag gh',
      code: 'gh',
      ctry: 'Ghana',
      natn: 'Ghanaian',
    },
    {
      flag: 'flag gi',
      code: 'gi',
      ctry: 'Gibraltar',
      natn: 'Gibraltan',
    },
    {
      flag: 'flag gl',
      code: 'gl',
      ctry: 'Greenland',
      natn: 'Greenlandian',
    },
    {
      flag: 'flag gm',
      code: 'gm',
      ctry: 'Gambia',
      natn: 'Gambian',
    },
    {
      flag: 'flag gn',
      code: 'gn',
      ctry: 'Guinea',
      natn: 'Guinean',
    },
    {
      flag: 'flag gp',
      code: 'gp',
      ctry: 'Guadeloupe',
      natn: 'Guadeloupe',
    },
    {
      flag: 'flag gq',
      code: 'gq',
      ctry: 'Equatorial Guinea',
      natn: 'Equatorial Guinean',
    },
    {
      flag: 'flag gr',
      code: 'gr',
      ctry: 'Greece',
      natn: 'Greek',
    },
    {
      flag: 'flag gs',
      code: 'gs',
      ctry: 'S. Georgia and S. Sandwich Islands',
      natn: 'S. Georgia and S. Sandwich Islands',
    },
    {
      flag: 'flag gt',
      code: 'gt',
      ctry: 'Guatemala',
      natn: 'Guatemalan',
    },
    {
      flag: 'flag gu',
      code: 'gu',
      ctry: 'Guam',
      natn: 'Guam',
    },
    {
      flag: 'flag gw',
      code: 'gw',
      ctry: 'Guinea-Bissau',
      natn: 'Guinea-Bissauan',
    },
    {
      flag: 'flag gy',
      code: 'gy',
      ctry: 'Guyana',
      natn: 'Guyanese',
    },
    {
      flag: 'flag hk',
      code: 'hk',
      ctry: 'Hong Kong',
      natn: 'Hong Kong',
    },
    {
      flag: 'flag hm',
      code: 'hm',
      ctry: 'Heard Island and McDonald Islands',
      natn: 'Heard Island and McDonald Islands',
    },
    {
      flag: 'flag hn',
      code: 'hn',
      ctry: 'Honduras',
      natn: 'Honduran',
    },
    {
      flag: 'flag hr',
      code: 'hr',
      ctry: 'Croatia (Hrvatska)',
      natn: 'Croatian (Hrvatska)',
    },
    {
      flag: 'flag ht',
      code: 'ht',
      ctry: 'Haiti',
      natn: 'Haitian',
    },
    {
      flag: 'flag hu',
      code: 'hu',
      ctry: 'Hungary',
      natn: 'Hungarian',
    },
    {
      flag: 'flag id',
      code: 'id',
      ctry: 'Indonesia',
      natn: 'Indonesian',
    },
    {
      flag: 'flag ie',
      code: 'ie',
      ctry: 'Ireland',
      natn: 'Irish',
    },
    {
      flag: 'flag il',
      code: 'il',
      ctry: 'Israel',
      natn: 'Israeli',
    },
    {
      flag: 'flag in',
      code: 'in',
      ctry: 'India',
      natn: 'Indian',
    },
    {
      flag: 'flag io',
      code: 'io',
      ctry: 'British Indian Ocean Territory',
      natn: 'British Indian Ocean Territory',
    },
    {
      flag: 'flag iq',
      code: 'iq',
      ctry: 'Iraq',
      natn: 'Iraqi',
    },
    {
      flag: 'flag ir',
      code: 'ir',
      ctry: 'Iran',
      natn: 'Iranian',
    },
    {
      flag: 'flag is',
      code: 'is',
      ctry: 'Iceland',
      natn: 'Icelander',
    },
    {
      flag: 'flag it',
      code: 'it',
      ctry: 'Italy',
      natn: 'Italian',
    },
    {
      flag: 'flag jm',
      code: 'jm',
      ctry: 'Jamaica',
      natn: 'Jamaican',
    },
    {
      flag: 'flag jo',
      code: 'jo',
      ctry: 'Jordan',
      natn: 'Jordanian',
    },
    {
      flag: 'flag jp',
      code: 'jp',
      ctry: 'Japan',
      natn: 'Japanese',
    },
    {
      flag: 'flag ke',
      code: 'ke',
      ctry: 'Kenya',
      natn: 'Kenyan',
    },
    {
      flag: 'flag kg',
      code: 'kg',
      ctry: 'Kyrgyzstan',
      natn: 'Kyrgyz',
    },
    {
      flag: 'flag kh',
      code: 'kh',
      ctry: 'Cambodia',
      natn: 'Cambodian',
    },
    {
      flag: 'flag ki',
      code: 'ki',
      ctry: 'Kiribati',
      natn: 'Kiribati',
    },
    {
      flag: 'flag km',
      code: 'km',
      ctry: 'Comoros',
      natn: 'Comoran',
    },
    {
      flag: 'flag kn',
      code: 'kn',
      ctry: 'Saint Kitts and Nevis',
      natn: 'Saint Kitts and Nevis',
    },
    {
      flag: 'flag kp',
      code: 'kp',
      ctry: 'Korea (North)',
      natn: 'North Korean',
    },
    {
      flag: 'flag kr',
      code: 'kr',
      ctry: 'Korea (South)',
      natn: 'South Korean',
    },
    {
      flag: 'flag kw',
      code: 'kw',
      ctry: 'Kuwait',
      natn: 'Kuwaiti',
    },
    {
      flag: 'flag ky',
      code: 'ky',
      ctry: 'Cayman Islands',
      natn: 'Cayman Islands',
    },
    {
      flag: 'flag kz',
      code: 'kz',
      ctry: 'Kazakhstan',
      natn: 'Kazakhstani',
    },
    {
      flag: 'flag la',
      code: 'la',
      ctry: 'Laos',
      natn: 'Laotian',
    },
    {
      flag: 'flag lb',
      code: 'lb',
      ctry: 'Lebanon',
      natn: 'Lebanese',
    },
    {
      flag: 'flag lc',
      code: 'lc',
      ctry: 'Saint Lucia',
      natn: 'Saint Lucian',
    },
    {
      flag: 'flag li',
      code: 'li',
      ctry: 'Liechtenstein',
      natn: 'Liechtensteiner',
    },
    {
      flag: 'flag lk',
      code: 'lk',
      ctry: 'Sri Lanka',
      natn: 'Sri Lankan',
    },
    {
      flag: 'flag lr',
      code: 'lr',
      ctry: 'Liberia',
      natn: 'Liberian',
    },
    {
      flag: 'flag ls',
      code: 'ls',
      ctry: 'Lesotho',
      natn: 'Lesotho',
    },
    {
      flag: 'flag lt',
      code: 'lt',
      ctry: 'Lithuania',
      natn: 'Lithuanian',
    },
    {
      flag: 'flag lu',
      code: 'lu',
      ctry: 'Luxembourg',
      natn: 'Luxembourger',
    },
    {
      flag: 'flag lv',
      code: 'lv',
      ctry: 'Latvia',
      natn: 'Latvian',
    },
    {
      flag: 'flag ly',
      code: 'ly',
      ctry: 'Libya',
      natn: 'Libyan',
    },
    {
      flag: 'flag ma',
      code: 'ma',
      ctry: 'Morocco',
      natn: 'Moroccan',
    },
    {
      flag: 'flag mc',
      code: 'mc',
      ctry: 'Monaco',
      natn: 'Monacan',
    },
    {
      flag: 'flag md',
      code: 'md',
      ctry: 'Moldova',
      natn: 'Moldovan',
    },
    {
      flag: 'flag mg',
      code: 'mg',
      ctry: 'Madagascar',
      natn: 'Madagascan',
    },
    {
      flag: 'flag mh',
      code: 'mh',
      ctry: 'Marshall Islands',
      natn: 'Marshall Islands',
    },
    {
      flag: 'flag mk',
      code: 'mk',
      ctry: 'Macedonia',
      natn: 'Macedonian',
    },
    {
      flag: 'flag ml',
      code: 'ml',
      ctry: 'Mali',
      natn: 'Malian',
    },
    {
      flag: 'flag mm',
      code: 'mm',
      ctry: 'Myanmar',
      natn: 'Myanmar',
    },
    {
      flag: 'flag mn',
      code: 'mn',
      ctry: 'Mongolia',
      natn: 'Mongolian',
    },
    {
      flag: 'flag mo',
      code: 'mo',
      ctry: 'Macao',
      natn: 'Macao',
    },
    {
      flag: 'flag mp',
      code: 'mp',
      ctry: 'Northern Mariana Islands',
      natn: 'Northern Mariana Islands',
    },
    {
      flag: 'flag mq',
      code: 'mq',
      ctry: 'Martinique',
      natn: 'Martinique',
    },
    {
      flag: 'flag mr',
      code: 'mr',
      ctry: 'Mauritania',
      natn: 'Mauritanian',
    },
    {
      flag: 'flag ms',
      code: 'ms',
      ctry: 'Montserrat',
      natn: 'Montserrat',
    },
    {
      flag: 'flag mt',
      code: 'mt',
      ctry: 'Malta',
      natn: 'Maltese',
    },
    {
      flag: 'flag mu',
      code: 'mu',
      ctry: 'Mauritius',
      natn: 'Mauritian',
    },
    {
      flag: 'flag mv',
      code: 'mv',
      ctry: 'Maldives',
      natn: 'Maldivan',
    },
    {
      flag: 'flag mw',
      code: 'mw',
      ctry: 'Malawi',
      natn: 'Malawian',
    },
    {
      flag: 'flag mx',
      code: 'mx',
      ctry: 'Mexico',
      natn: 'Mexican',
    },
    {
      flag: 'flag my',
      code: 'my',
      ctry: 'Malaysia',
      natn: 'Malaysian',
    },
    {
      flag: 'flag mz',
      code: 'mz',
      ctry: 'Mozambique',
      natn: 'Mozambican',
    },
    {
      flag: 'flag na',
      code: 'na',
      ctry: 'Namibia',
      natn: 'Namibian',
    },
    {
      flag: 'flag nc',
      code: 'nc',
      ctry: 'New Caledonia',
      natn: 'New Caledonian',
    },
    {
      flag: 'flag ne',
      code: 'ne',
      ctry: 'Niger',
      natn: 'Nigerien',
    },
    {
      flag: 'flag nf',
      code: 'nf',
      ctry: 'Norfolk Island',
      natn: 'Norfolk Island',
    },
    {
      flag: 'flag ng',
      code: 'ng',
      ctry: 'Nigeria',
      natn: 'Nigerian',
    },
    {
      flag: 'flag ni',
      code: 'ni',
      ctry: 'Nicaragua',
      natn: 'Nicaraguan',
    },
    {
      flag: 'flag nl',
      code: 'nl',
      ctry: 'Netherlands',
      natn: 'Dutch',
    },
    {
      flag: 'flag no',
      code: 'no',
      ctry: 'Norway',
      natn: 'Norwegian',
    },
    {
      flag: 'flag np',
      code: 'np',
      ctry: 'Nepal',
      natn: 'Nepalese',
    },
    {
      flag: 'flag nr',
      code: 'nr',
      ctry: 'Nauru',
      natn: 'Nauruan',
    },
    {
      flag: 'flag nu',
      code: 'nu',
      ctry: 'Niue',
      natn: 'Niue',
    },
    {
      flag: 'flag nz',
      code: 'nz',
      ctry: 'New Zealand',
      natn: 'New Zealander',
    },
    {
      flag: 'flag om',
      code: 'om',
      ctry: 'Oman',
      natn: 'Omani',
    },
    {
      flag: 'flag pa',
      code: 'pa',
      ctry: 'Panama',
      natn: 'Panamanian',
    },
    {
      flag: 'flag pe',
      code: 'pe',
      ctry: 'Peru',
      natn: 'Peruvian',
    },
    {
      flag: 'flag pf',
      code: 'pf',
      ctry: 'French Polynesia',
      natn: 'French Polynesian',
    },
    {
      flag: 'flag pg',
      code: 'pg',
      ctry: 'Papua New Guinea',
      natn: 'Papua New Guinean',
    },
    {
      flag: 'flag ph',
      code: 'ph',
      ctry: 'Philippines',
      natn: 'Filipino',
    },
    {
      flag: 'flag pk',
      code: 'pk',
      ctry: 'Pakistan',
      natn: 'Pakistani',
    },
    {
      flag: 'flag pl',
      code: 'pl',
      ctry: 'Poland',
      natn: 'Polish',
    },
    {
      flag: 'flag pm',
      code: 'pm',
      ctry: 'Saint Pierre and Miquelon',
      natn: 'Saint Pierre and Miquelon',
    },
    {
      flag: 'flag pn',
      code: 'pn',
      ctry: 'Pitcairn',
      natn: 'Pitcairn',
    },
    {
      flag: 'flag pr',
      code: 'pr',
      ctry: 'Puerto Rico',
      natn: 'Puerto Rican',
    },
    {
      flag: 'flag ps',
      code: 'ps',
      ctry: 'Palestinian Territory',
      natn: 'Palestinian',
    },
    {
      flag: 'flag pt',
      code: 'pt',
      ctry: 'Portugal',
      natn: 'Portugese',
    },
    {
      flag: 'flag pw',
      code: 'pw',
      ctry: 'Palau',
      natn: 'Palauan',
    },
    {
      flag: 'flag py',
      code: 'py',
      ctry: 'Paraguay',
      natn: 'Paraguayan',
    },
    {
      flag: 'flag qa',
      code: 'qa',
      ctry: 'Qatar',
      natn: 'Qatari',
    },
    {
      flag: 'flag re',
      code: 're',
      ctry: 'Reunion',
      natn: 'Reunion',
    },
    {
      flag: 'flag ro',
      code: 'ro',
      ctry: 'Romania',
      natn: 'Romanian',
    },
    {
      flag: 'flag ru',
      code: 'ru',
      ctry: 'Russian Federation',
      natn: 'Russian',
    },
    {
      flag: 'flag rw',
      code: 'rw',
      ctry: 'Rwanda',
      natn: 'Rwandan',
    },
    {
      flag: 'flag sa',
      code: 'sa',
      ctry: 'Saudi Arabia',
      natn: 'Saudi Arabia', //?
    },
    {
      flag: 'flag sb',
      code: 'sb',
      ctry: 'Solomon Islands',
      natn: 'Solomon Islands',
    },
    {
      flag: 'flag sc',
      code: 'sc',
      ctry: 'Seychelles',
      natn: 'Seychellois',
    },
    {
      flag: 'flag sd',
      code: 'sd',
      ctry: 'Sudan',
      natn: 'Sudanese',
    },
    {
      flag: 'flag se',
      code: 'se',
      ctry: 'Sweden',
      natn: 'Swedish',
    },
    {
      flag: 'flag sg',
      code: 'sg',
      ctry: 'Singapore',
      natn: 'Singaporean',
    },
    {
      flag: 'flag sh',
      code: 'sh',
      ctry: 'Saint Helena',
      natn: 'Saint Helena',
    },
    {
      flag: 'flag si',
      code: 'si',
      ctry: 'Slovenia',
      natn: 'Slovenian',
    },
    {
      flag: 'flag sj',
      code: 'sj',
      ctry: 'Svalbard and Jan Mayen',
      natn: 'Svalbard and Jan Mayen',
    },
    {
      flag: 'flag sk',
      code: 'sk',
      ctry: 'Slovakian',
      natn: 'Slovakia',
    },
    {
      flag: 'flag sl',
      code: 'sl',
      ctry: 'Sierra Leone',
      natn: 'Sierra Leonean',
    },
    {
      flag: 'flag sm',
      code: 'sm',
      ctry: 'San Marino',
      natn: 'San Marinese',
    },
    {
      flag: 'flag sn',
      code: 'sn',
      ctry: 'Senegal',
      natn: 'Senegalese',
    },
    {
      flag: 'flag so',
      code: 'so',
      ctry: 'Somalia',
      natn: 'Somali',
    },
    {
      flag: 'flag sr',
      code: 'sr',
      ctry: 'Suriname',
      natn: 'Surinamer',
    },
    {
      flag: 'flag st',
      code: 'st',
      ctry: 'Sao Tome and Principe',
      natn: 'Sao Tomean',
    },
    {
      flag: 'flag sv',
      code: 'sv',
      ctry: 'El Salvador',
      natn: 'Salvadoran',
    },
    {
      flag: 'flag sy',
      code: 'sy',
      ctry: 'Syria',
      natn: 'Syrian',
    },
    {
      flag: 'flag sz',
      code: 'sz',
      ctry: 'Swaziland',
      natn: 'Swazi',
    },
    {
      flag: 'flag tc',
      code: 'tc',
      ctry: 'Turks and Caicos Islands',
      natn: 'Turks and Caicos Islands',
    },
    {
      flag: 'flag td',
      code: 'td',
      ctry: 'Chad',
      natn: 'Chadian',
    },
    {
      flag: 'flag tf',
      code: 'tf',
      ctry: 'French Southern Territories',
      natn: 'French Southern Territories',
    },
    {
      flag: 'flag tg',
      code: 'tg',
      ctry: 'Togo',
      natn: 'Togolese',
    },
    {
      flag: 'flag th',
      code: 'th',
      ctry: 'Thailand',
      natn: 'Thai',
    },
    {
      flag: 'flag tj',
      code: 'tj',
      ctry: 'Tajikistan',
      natn: 'Tajik',
    },
    {
      flag: 'flag tk',
      code: 'tk',
      ctry: 'Tokelau',
      natn: 'Tokelau',
    },
    {
      flag: 'flag tl',
      code: 'tl',
      ctry: 'Timor-Leste',
      natn: 'Timor-Leste',
    },
    {
      flag: 'flag tm',
      code: 'tm',
      ctry: 'Turkmenistan',
      natn: 'Turkmene',
    },
    {
      flag: 'flag tn',
      code: 'tn',
      ctry: 'Tunisia',
      natn: 'Tunisian',
    },
    {
      flag: 'flag to',
      code: 'to',
      ctry: 'Tonga',
      natn: 'Tongan',
    },
    {
      flag: 'flag tp',
      code: 'tp',
      ctry: 'East Timor',
      natn: 'East Timorese',
    },
    {
      flag: 'flag tr',
      code: 'tr',
      ctry: 'Turkey',
      natn: 'Turkish',
    },
    {
      flag: 'flag tt',
      code: 'tt',
      ctry: 'Trinidad and Tobago',
      natn: 'Trinidadian or Tobagonian',
    },
    {
      flag: 'flag tv',
      code: 'tv',
      ctry: 'Tuvalu',
      natn: 'Tuvaluan',
    },
    {
      flag: 'flag tw',
      code: 'tw',
      ctry: 'Taiwan',
      natn: 'Taiwanese',
    },
    {
      flag: 'flag tz',
      code: 'tz',
      ctry: 'Tanzania',
      natn: 'Tanzanian',
    },
    {
      flag: 'flag ua',
      code: 'ua',
      ctry: 'Ukraine',
      natn: 'Ukrainian',
    },
    {
      flag: 'flag ug',
      code: 'ug',
      ctry: 'Uganda',
      natn: 'Ugandan',
    },
    {
      flag: 'flag uk',
      code: 'uk',
      ctry: 'United Kingdom',
      natn: 'United Kingdom', //?
    },
    {
      flag: 'flag um',
      code: 'um',
      ctry: 'United States Minor Outlying Islands',
      natn: 'United States Minor Outlying Islands',
    },
    {
      flag: 'flag us',
      code: 'us',
      ctry: 'United States',
      natn: 'US American',
    },
    {
      flag: 'flag uy',
      code: 'uy',
      ctry: 'Uruguay',
      natn: 'Uruguayan',
    },
    {
      flag: 'flag uz',
      code: 'uz',
      ctry: 'Uzbekistan',
      natn: 'Uzbekistani',
    },
    {
      flag: 'flag va',
      code: 'va',
      ctry: 'Vatican City State (Holy See)',
      natn: 'Vatican City State (Holy See)',
    },
    {
      flag: 'flag vc',
      code: 'vc',
      ctry: 'Saint Vincent and the Grenadines',
      natn: 'Saint Vincent and the Grenadines',
    },
    {
      flag: 'flag ve',
      code: 've',
      ctry: 'Venezuela',
      natn: 'Venezuelan',
    },
    {
      flag: 'flag vg',
      code: 'vg',
      ctry: 'Virgin Islands (British)',
      natn: 'Virgin Islands (British)',
    },
    {
      flag: 'flag vi',
      code: 'vi',
      ctry: 'Virgin Islands (U.S.)',
      natn: 'Virgin Islands (U.S.)',
    },
    {
      flag: 'flag vn',
      code: 'vn',
      ctry: 'Vietnam',
      natn: 'Vietnamnese',
    },
    {
      flag: 'flag vu',
      code: 'vu',
      ctry: 'Vanuatu',
      natn: 'Vanuatu',
    },
    {
      flag: 'flag wf',
      code: 'wf',
      ctry: 'Wallis and Futuna',
      natn: 'Wallis and Futuna',
    },
    {
      flag: 'flag ws',
      code: 'ws',
      ctry: 'Samoa',
      natn: 'Samoan',
    },
    {
      flag: 'flag ye',
      code: 'ye',
      ctry: 'Yemen',
      natn: 'Yemenite',
    },
    {
      flag: 'flag yt',
      code: 'yt',
      ctry: 'Mayotte',
      natn: 'Mayotte',
    },
    {
      flag: 'flag za',
      code: 'za',
      ctry: 'South Africa',
      natn: 'South African',
    },
    {
      flag: 'flag zm',
      code: 'zm',
      ctry: 'Zambia',
      natn: 'Zambian',
    },
    {
      flag: 'flag zw',
      code: 'zw',
      ctry: 'Zimbabwe',
      natn: 'Zimbabwean'
    }
  ];

  this.getForCode = function(code) {
    for (var index in this.nationalities) {
      if (this.nationalities[index].code === code) {
        return this.nationalities[index];
      }
    }
  };

  this.promise = function(query, property) {
    if (!query) {query = '.*';} else {query = query.toLowerCase();}
    if (!property) {property = 'natn';}
    var filtered = this.nationalities.filter(function(element) {
      return element[property].toLowerCase().match(query) !== null;
    });
    var deferred = $q.defer();
    deferred.resolve(filtered);
    return deferred.promise;
  };
});